# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lolita-report}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ITHouse (Latvia)", "Arturs Meisters", "Artjoms Tjangins"]
  s.date = %q{2011-04-19}
  s.description = %q{Enable configuration and generate HTML view for Lolita resources, and also has ability to export to different formats.}
  s.email = %q{support@ithouse.lv}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/lolita/reports_controller.rb",
    "app/reports/default_report.rb",
    "app/views/lolita/reports/show.html.erb",
    "author",
    "doc/ActiveSupport.html",
    "doc/ActiveSupport/TestCase.html",
    "doc/Comment.html",
    "doc/Gemfile.html",
    "doc/LICENSE.html",
    "doc/Lolita.html",
    "doc/Lolita/Configuration.html",
    "doc/Lolita/Configuration/Report.html",
    "doc/Lolita/Configuration/Reports.html",
    "doc/LolitaReport.html",
    "doc/LolitaReport/Configuration.html",
    "doc/Post.html",
    "doc/Rakefile.html",
    "doc/author.html",
    "doc/created.rid",
    "doc/images/brick.png",
    "doc/images/brick_link.png",
    "doc/images/bug.png",
    "doc/images/bullet_black.png",
    "doc/images/bullet_toggle_minus.png",
    "doc/images/bullet_toggle_plus.png",
    "doc/images/date.png",
    "doc/images/find.png",
    "doc/images/loadingAnimation.gif",
    "doc/images/macFFBgHack.png",
    "doc/images/package.png",
    "doc/images/page_green.png",
    "doc/images/page_white_text.png",
    "doc/images/page_white_width.png",
    "doc/images/plugin.png",
    "doc/images/ruby.png",
    "doc/images/tag_green.png",
    "doc/images/wrench.png",
    "doc/images/wrench_orange.png",
    "doc/images/zoom.png",
    "doc/index.html",
    "doc/js/darkfish.js",
    "doc/js/jquery.js",
    "doc/js/quicksearch.js",
    "doc/js/thickbox-compressed.js",
    "doc/lib/lolita-report/configuration/base_rb.html",
    "doc/lib/lolita-report/configuration/report_rb.html",
    "doc/lib/lolita-report/configuration/reports_rb.html",
    "doc/lib/lolita-report/version_rb.html",
    "doc/lib/lolita-report_rb.html",
    "doc/rdoc.css",
    "doc/spec/configuration/report_spec_rb.html",
    "doc/spec/configuration/reports_spec_rb.html",
    "doc/spec/factories/factories_rb.html",
    "doc/spec/orm/mongoid_rb.html",
    "doc/spec/spec_helper_rb.html",
    "lib/generators/lolita_report/assets_generator.rb",
    "lib/generators/lolita_report/install_generator.rb",
    "lib/lolita-report.rb",
    "lib/lolita-report/configuration/base.rb",
    "lib/lolita-report/configuration/report.rb",
    "lib/lolita-report/configuration/reports.rb",
    "lib/lolita-report/module.rb",
    "lib/lolita-report/rails.rb",
    "lib/lolita-report/routes.rb",
    "lolita-report.gemspec",
    "public/images/xls.png",
    "spec/configuration/report_spec.rb",
    "spec/configuration/reports_spec.rb",
    "spec/factories/factories.rb",
    "spec/orm/mongoid.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/ithouse/lolita-report}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{Report plugin for Lolita 3}
  s.test_files = [
    "spec/configuration/report_spec.rb",
    "spec/configuration/reports_spec.rb",
    "spec/factories/factories.rb",
    "spec/orm/mongoid.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<lolita>, ["~> 3.1.4"])
      s.add_runtime_dependency(%q<ruport>, [">= 0"])
      s.add_runtime_dependency(%q<spreadsheet>, [">= 0"])
      s.add_development_dependency(%q<factory_girl_rails>, [">= 0"])
      s.add_development_dependency(%q<cover_me>, [">= 1.0.0.rc6"])
      s.add_development_dependency(%q<mongoid>, ["~> 2.0.0.beta"])
      s.add_development_dependency(%q<bson_ext>, [">= 1.0.9"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
    else
      s.add_dependency(%q<lolita>, ["~> 3.1.4"])
      s.add_dependency(%q<ruport>, [">= 0"])
      s.add_dependency(%q<spreadsheet>, [">= 0"])
      s.add_dependency(%q<factory_girl_rails>, [">= 0"])
      s.add_dependency(%q<cover_me>, [">= 1.0.0.rc6"])
      s.add_dependency(%q<mongoid>, ["~> 2.0.0.beta"])
      s.add_dependency(%q<bson_ext>, [">= 1.0.9"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    end
  else
    s.add_dependency(%q<lolita>, ["~> 3.1.4"])
    s.add_dependency(%q<ruport>, [">= 0"])
    s.add_dependency(%q<spreadsheet>, [">= 0"])
    s.add_dependency(%q<factory_girl_rails>, [">= 0"])
    s.add_dependency(%q<cover_me>, [">= 1.0.0.rc6"])
    s.add_dependency(%q<mongoid>, ["~> 2.0.0.beta"])
    s.add_dependency(%q<bson_ext>, [">= 1.0.9"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
  end
end

